feat: Sprint 14 HW
pavlovAndrei/java-shareit pull request #2
Opened 2023-01-09 13:41 UTC by pavlovAndrei

2023-01-09 17:47 UTC, EugeneLenkevich requested changes
Привет, Андрей, спасибо за PR

В обшем, все очень круто сделано :) 
Ничего лишнего, я отметил некоторые незначительные моменты, главное закомментированный код давай почистим, а то как то в глаза бросается :)

2023-01-09 17:47 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @ManyToOne(fetch = FetchType.EAGER)
Там дже и так по умолчанию fetch = FetchType.EAGER, можно наверно и не указывать :)

2023-01-09 17:47 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case ALL:
Если есть желание можешь попробовать применить паттерн "стратегия"

Возможно, именно для этого случая стратегия покажется избыточной (обработчики все в одну строчку), но попробовать самое то, к тому же в реальной жизни часто используется, так как часто в обработчике бывает нетривиальная логика и куча своих зависимостей :) 

Смысл такой. У тебя есть соответствие между состоянием и обработчиком этого состояния.
Можно сделать мапу
Map<String, BookingStateFetchStrategy>, где BookingStateFetchStrategy - который будут реализовывать обработчики состояния

или же, более простой вариант, в мапу засунуть методы сервиса, примерно так будет
Map<State, Supplier> handlers = ...
handlers.put(ALL, this::handleAllState) 

То есть, мы заменяем switch на поиск нужного обработчика через map :)

https://ravthiru.medium.com/strategy-design-pattern-with-in-spring-boot-application-2ff5a7486cd8

2023-01-09 17:47 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (!userRepository.existsById(userId)) {
Ага, супер, пожалуй самый оптимальный способ проверки сущестовования записи :)

2023-01-09 17:47 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/handler/ErrorHandler.java
> +//    @ExceptionHandler
Закоментированный код лучш не оставлять. Его потом трудно будет обратно приделать потому что, скорее всего, все вокруг поменяется, а для истории есть git :)

2023-01-09 17:47 UTC, EugeneLenkevich commented on src/main/resources/schema.sql
> +    description  VARCHAR(200),
200 символов на описание наверно маловато, тут лучше побольше поставить, например varchar(2000) или вовсе text :)

2023-01-10 07:59 UTC, pavlovAndrei commented on src/main/resources/schema.sql
> +    description  VARCHAR(200),
Поменял

2023-01-10 07:59 UTC, pavlovAndrei commented on src/main/java/ru/practicum/shareit/handler/ErrorHandler.java
> +//    @ExceptionHandler
Да, спасибо, хотел удалить и забыл

2023-01-10 08:00 UTC, pavlovAndrei commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case ALL:
Попробовал добавить стратегии для одного из swither-ов. Посмотри, плиз

2023-01-10 08:00 UTC, pavlovAndrei commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @ManyToOne(fetch = FetchType.EAGER)
Ага, убрал. Верно, там оно по дефолту

2023-01-10 08:27 UTC, EugeneLenkevich approved these changes
Да, все супер, спасибо

Наша стратегия, конечно, с первого взгляда не факт что выглядит более элегантно чем свич, банально потому, что у нас вся логика на одну строчку на каждый статус, ее плюсы более очевидны когда логики побольше, но зато добавлять новую логику стало проще и  мы применили паттерн, который очень часто  используется в продакшн-коде :)

2023-01-10 08:27 UTC, pavlovAndrei commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case ALL:
Переиспользовал стратегии и для второго свитчера. Так лаконичнее получилось.

2023-01-10 08:29 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case ALL:
> Попробовал добавить стратегии для одного из swither-ов. Посмотри, плиз

Да, норм, так это и работает :)

2023-01-10 08:31 UTC, pavlovAndrei commented
> Да, все супер, спасибо
> 
> Наша стратегия, конечно, с первого взгляда не факт что выглядит более элегантно чем свич, банально потому, что у нас вся логика на одну строчку на каждый статус. Ее плюсы более очевидны когда логики побольше, но, зато, добавлять новую логику стало проще и мы применили паттерн, который очень часто используется в продакшн-коде :)

Я переделал и для второго свича и вот тут стратегии себя уже лучше показали - по сути,  все функции завязанные на наш стейт можно добавлять в стратегию, просто расширяя интерфейс

2023-01-10 08:35 UTC, EugeneLenkevich commented
>  по сути, все функции завязанные на наш стейт можно добавлять в стратегию, просто расширяя интерфейс

Таки да, именно так оно и работает :)

2023-01-11 13:03 UTC, merged